name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Base
        uses: lowlighter/metrics@latest
        with:
          filename: base.metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          base_indepth: yes
          base_hireable: yes
      - name: Notable
        uses: lowlighter/metrics@latest
        with:
          config_padding: 0, 10
          filename: notable.metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
      - name: Followup
        uses: lowlighter/metrics@latest
        with:
          filename: followup.metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: user
      - name: Activity
        uses: lowlighter/metrics@latest
        with:
          filename: activity.metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 3
          plugin_activity_days: 0
      - name: Habits
        uses: lowlighter/metrics@latest
        with:
          filename: habits.metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: Asia/Kolkata
      - name: Stars
        uses: lowlighter/metrics@latest
        with:
          filename: stars.metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3

          
          





